trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - .vscode/*
    - README.md
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - .vscode/*
    - README.md

resources:
- repo: self

jobs:
  - job: Build_PS_Win2016
    pool:
      vmImage: vs2017-win2016
    steps:
    - powershell: |
        #Install nuget provider
        Get-PackageProvider -Name NuGet -ForceBootstrap | Out-Null
        #Install modules
        Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
        Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
        Install-Module psake -Force -Scope CurrentUser
      displayName: 'Install prereqs'
    - powershell: |
        Invoke-PSake .\build.psake.ps1 -taskList Test
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PS_Win2016'
      displayName: 'Publish Test Results'