trigger: none
pr: none

resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: PowerShell@2
  displayName: 'Build and Test'
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    arguments: '-Verbose'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'PS_Win2016'